
platform :ios do
  lane :ios_build do
    cocoapods(
      clean_install: true,
      podfile: "./ios/Podfile"
    )
    xcclean(
      workspace: "./ios/GithubRepoSearch.xcworkspace",
      scheme: "GithubRepoSearch"
    )
    xcbuild(
      workspace: "./ios/GithubRepoSearch.xcworkspace",
      scheme: "GithubRepoSearch"
    )
  end
  desc "Push a new beta build to TestFlight"
  lane :build do
    cocoapods(
      clean_install: true,
      podfile: "./ios/Podfile"
    )
    app_version = get_version_number(xcodeproj: "./ios/GithubRepoSearch.xcodeproj", target: "GithubRepoSearch")
    new_build_number = latest_testflight_build_number(version: app_version, initial_build_number: 0) + 1
    increment_build_number(build_number: new_build_number, xcodeproj: "./ios/GithubRepoSearch.xcodeproj")
    build_app(
      workspace: "./ios/GithubRepoSearch.xcworkspace", 
      scheme: "GithubRepoSearch",
      clean: true,
    )
  end
  lane :test_flight do
    changelog_from_git_commits
    upload_to_testflight(
      beta_app_review_info: {
        contact_email: "lee.wei.jun@rhbgroup.com",
        contact_first_name: "Jason",
        contact_last_name: "Lee",
        contact_phone: "12345678",
        demo_account_name: "demo",
        demo_account_password: "demo"
      }, 
      skip_waiting_for_build_processing: false, 
      distribute_external: true, 
      groups: ["SIT"], 
    )
  end
  lane :beta do
    build
  end
end

platform :android do
  # Android Lanes
end